WOVNio/wovnjava

.idea/encodings.xml
.travis.yml
circle.yml
pom.xml
src/main/java/com/github/wovnio/wovnjava/Headers.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
src/test/java/com/github/wovnio/wovnjava/SettingsTest.java

* Remove Matcher.group(string) functions for supporting Java 6.
* Fix query setting bug.
* Create JAR file including all dependencies on CircleCI.

Support Java 6

---

src/main/java/com/github/wovnio/wovnjava/Headers.java
src/main/java/com/github/wovnio/wovnjava/Interceptor.java

#20 
http://docs.oracle.com/javase/6/docs/api/java/util/regex/Matcher.html
> The matches method attempts to match the entire input sequence against the pattern.
"matches" method is not what I think. All "matches" methods were replaced with "find" methods.

Fix query mode bug.

---

.idea/compiler.xml
pom.xml
wovn-servlet-filter.iml

* Set compiler version.
* Set source encoding.

Fix pom.xml for suppressing warnings.

---

src/main/java/com/github/wovnio/wovnjava/Store.java

Some exceptions in Store.java were wrong or ignored.

Fix/Add exceptions in Store.java.

---

src/main/java/com/github/wovnio/wovnjava/Headers.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java

* Implement useProxy option. (default value is false)
* When useProxy is true, wovnjava uses X-Forwarded-Host value in header instead of getRemoteHost() and getServerName().

Support reverse proxy.

---

.idea/uiDesigner.xml
src/main/java/com/github/wovnio/wovnjava/Headers.java
src/main/java/com/github/wovnio/wovnjava/Interceptor.java
src/main/java/com/github/wovnio/wovnjava/Utf8.java
src/main/java/com/github/wovnio/wovnjava/WovnHttpServletResponse.java

Support non UTF-8 encodings.

---

.idea/encodings.xml
src/main/java/com/github/wovnio/wovnjava/Interceptor.java
src/main/java/com/github/wovnio/wovnjava/Logger.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/main/java/com/github/wovnio/wovnjava/Store.java
src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java

* Implement debugMode setting.
* When debugMode is 1, wovnjava outputs debug logs.

Implement debug mode.

---

src/main/java/com/github/wovnio/wovnjava/Headers.java
src/test/java/com/github/wovnio/wovnjava/HeadersTest.java

In the following case, query should be emtpy string.
* query paramter: "p"
* page url: "localhost/?q=1"

Fix wrong case that query parameter is not empty.

---

src/main/java/com/github/wovnio/wovnjava/Headers.java
src/test/java/com/github/wovnio/wovnjava/HeadersTest.java

Port number had not been included in URL.

Fix wrong API request URL.

---

.gitignore
Vagrantfile
provision.sh

This is my developing environment.

Add Vagrantfile.

---

src/main/java/com/github/wovnio/wovnjava/Interceptor.java
src/main/java/com/github/wovnio/wovnjava/Lang.java
src/test/java/com/github/wovnio/wovnjava/LangTest.java
wovn-servlet-filter.iml

Fixed wovnjava like wovnrb.
https://github.com/WOVNio/wovnrb/pull/46

Correct Chinese hreflang.

---

src/main/java/com/github/wovnio/wovnjava/Store.java

Set user agent

---

.gitignore
src/main/java/com/github/wovnio/wovnjava/Lang.java
src/test/java/com/github/wovnio/wovnjava/LangTest.java

https://github.com/WOVNio/wovnjava/issues/55
Adding missing languages

adding missing languages

---

src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

Relate: https://github.com/WOVNio/equalizer/issues/9799
Disable pretty print for reduce html size.

Disable pretty print

---

README.md
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
src/test/java/com/github/wovnio/wovnjava/TestUtil.java

Implement HTML class ignore.

---

src/main/java/com/github/wovnio/wovnjava/WovnHttpServletRequest.java
src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java

Allow client to get current lang code with `.getHeader("X-Wovn-Lang")`

Feature X-Wovn-Lang header

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/Headers.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/main/java/com/github/wovnio/wovnjava/WovnHttpServletResponse.java
src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
src/test/java/com/github/wovnio/wovnjava/TestUtil.java

Relate: https://github.com/WOVNio/equalizer/issues/11477
Replace `Location` header correctly.

Support location correctly without test

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/Lang.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/test/java/com/github/wovnio/wovnjava/LangTest.java

Add support for Tagalog language

Add support for Tagalog language

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/Settings.java

Bump version to 0.4.2 for releasing new changes.
**Remember to release new version on Jitpack after merging this**

Bump version to 0.4.2

---

src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/test/java/com/github/wovnio/wovnjava/TestUtil.java

`devMode` will set the snippet URL and translation API URL to match development environment.
Set it as follows
```xml
<init-param>
<param-name>devMode</param-name>
<param-value>1</param-value>
</init-param>
```

Add devMode setting

---

src/main/java/com/github/wovnio/wovnjava/WovnHttpServletRequest.java
src/main/java/com/github/wovnio/wovnjava/WovnHttpServletResponse.java
src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java

Add `@Override` tags to all relevant functions

Add Override tags

---

pom.xml

Remember to create a new version for Jitpack after merging this PR.

Bump version to 0.4.3

---

src/main/java/com/github/wovnio/wovnjava/Api.java
src/main/java/com/github/wovnio/wovnjava/Interceptor.java
src/main/java/com/github/wovnio/wovnjava/ResponseHeaders.java
src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
src/test/java/com/github/wovnio/wovnjava/ApiTest.java
src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
src/test/java/com/github/wovnio/wovnjava/ResponseHeadersTest.java

Improve naming for variables added in https://github.com/WOVNio/wovnjava/pull/94
I considered including this in the next debugging PR, but it touched enough files that I figured it was better to do it separately.

Update naming for variables related to API HTTP headers

---

src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java

For debugging, we added a "wovnDisable" mode to make wovnjava not manipulate the request or response. I recommend us to change the behavior for disable mode slightly.
Completely disabling wovnjava seems to not result in the behavior we want. We need it to at least strip the language code from the URL, so that the request can be successfully passed on to the server endpoint below.
For wovnjava, this means changing
```java
chain.doFilter(request, response);
```
into
```java
WovnHttpServletRequest wovnRequest = new WovnHttpServletRequest((HttpServletRequest)request, headers);
chain.doFilter(wovnRequest, response);
```
Additionally, I would like to set the `X-Wovn-Handler` HTTP header even for requests in disable mode, so that we can know that wovnjava sees the request.
Therefore, I moved …

Strip language code and set X-Wovn-Handler also for wovnDisable mode

---

src/main/java/com/github/wovnio/wovnjava/Headers.java
src/main/java/com/github/wovnio/wovnjava/UrlPath.java
src/test/java/com/github/wovnio/wovnjava/UrlPathTest.java

I want to clean up URL management in order to address some bugs related to it.
As part of that effort, I want to extract some URL manipulation functions into its own file so they can be tested separately. It will also let me use the functions outside of Headers if I need to.
The functions are moved over untouched.

Extract and test URL manipulation functions

---

src/main/java/com/github/wovnio/wovnjava/Headers.java

Variables `unmaskedHost`, `unmaskedPathName`, and `unmaskedUrl` were set but never used.

Remove unused code from Headers.java

---

src/main/java/com/github/wovnio/wovnjava/Headers.java
src/main/java/com/github/wovnio/wovnjava/Interceptor.java
src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
src/main/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandler.java
src/main/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandler.java
src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandler.java
src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
src/test/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandlerTest.java
src/test/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandlerTest.java

* Set final variables for request state in Headers constructor
- `clientRequestUrlWithoutLangCode`
- `shouldRedirectToDefaultLang`
- `isValidPath`
* Use UrlLanguagePatternHandler to check if request URL matches sitePrefixPath
* Ensure that `removeLang` accepts being called with empty language argument

[Refactor] Set request state final variables

---

pom.xml

Bump version for release of the work with URL management up until this point

Set version 0.6.0

---

src/main/java/com/github/wovnio/wovnjava/Headers.java
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/main/java/com/github/wovnio/wovnjava/Interceptor.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
src/test/java/com/github/wovnio/wovnjava/SettingsTest.java

Refactor settings to store `defaultLang` and `supportedLangs` settings as Lang objects instead of String

Store language settings as Lang objects

---

README.md
pom.xml

With this, we are releasing wovnjava version 1.0!
----
Wovnjava version 1.0 has improved request handling, improved user experience for configuration, and includes a new customizable URL management option. Start of semantic versioning.
* Redesigned settings management
- Unused settings removed
- Better error messages for incorrect configuration
- Updated configuration instructions
* Improved request handling
- Predictable URL manipulations
- Better handling and detection for requests that should not be intercepted
* Custom Domain setting
- Allow customizable URLs for each supported language
----
This PR changes include some light adjustments to language and formatting for README.
_I mistakenly created a jitpack release for 1.0.0 without bumping version in pom.xml. Therefore, this becomes …

Adjust settings instructions and bump version to 1.0

---

.circleci/config.yml

_Note:_ target branch is not master, but a separate branch for Java 7 support

Add circleci test jobs for oraclejdk7 and openjdk7

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/FileExtensionMatcher.java
src/test/java/com/github/wovnio/wovnjava/FileExtensionMatcherTest.java

Added doc/docx/xls/xls/xlsx/xlsx/xlsm pattern for file recognition.

[Hotfix] Adjust doc file regex

---

README.en.md

Additional notes on common problems.

Added a note about the filter settings.

---

README.en.md
README.ja.md
pom.xml
src/main/java/com/github/wovnio/wovnjava/Lang.java

https://wovnio.atlassian.net/browse/ST-381
Add Khmer language support

Add Khmer language support

---

.gitignore
pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

https://wovnio.atlassian.net/browse/ST-345
Treat data-wovn-ignore the same as wovn-ignore

Support data-wovn-ignore attribute

---

DEVELOPERS.md

How to compile for java6 and how to use locally compiled wovnjava with docker

Added developer instructions on how to compile for java6

---

CONTRIBUTE.md

Added instructions on how to compile to develop

Added explain for developing.

---

DEVELOPERS.md
docker/README.md
docker/java6/Makefile
docker/java6/hello/pom.local.xml
docker/java6/hello/pom.xml
docker/java6/maven-clean-package.sh
docker/java6/mvn.sh
maven3-jdk6-clean.sh
maven3-jdk6.sh

The Makefile has been modified to make it easier to use locally compiled libraries.

Clean up docker environment

---

README.en.md
README.ja.md
pom.xml
src/main/java/com/github/wovnio/wovnjava/Lang.java

https://wovnio.atlassian.net/browse/ST-525
Add Tamil and Sinhala support

Add Tamil and Sinhala support

---

docker/java7/hello/src/main/webapp/page.jsp
docker/java7/hello/src/main/webapp/redirecting_page.jsp
docker/java7/hello/src/main/webapp/redirection_target.jsp
docker/java8/docker-compose.yml
docker/java8/hello/src/main/webapp/page.jsp
docker/java8/hello/src/main/webapp/redirecting_page.jsp
docker/java8/hello/src/main/webapp/redirection_target.jsp

https://wovnio.atlassian.net/browse/ST-698
Routes added:
/page.jsp : a simple page
/redirecting_page.jsp :  a page that will redirect you to /redirection_target.jsp

Add more test pages to docker

---

README.en.md
pom.xml
src/main/java/com/github/wovnio/wovnjava/Api.java
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/test/java/com/github/wovnio/wovnjava/SettingsTest.java

Cherry pick (#171)
Minor version bump to 1.7.0

Cherry pick feature: Add outboundProxyHost/Port settings to enable communication with html swapper via a proxy.

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

https://wovnio.atlassian.net/browse/ST-898
Make wovnjava add hreflangs before sending non-source language HTML to html-swapper.

Fix missing hreflang

---

docker/java7/docker-compose.yml
docker/java8/docker-compose.yml

https://wovnio.atlassian.net/browse/ST-699
See https://github.com/WOVNio/backend_library_integration_tests/pull/3

[ST-699] Use explicit docker network to help with CI integration tests

---

src/main/java/com/github/wovnio/wovnjava/CustomDomainLanguageValidator.java
src/main/java/com/github/wovnio/wovnjava/FileExtensionMatcher.java
src/main/java/com/github/wovnio/wovnjava/HtmlChecker.java
src/main/java/com/github/wovnio/wovnjava/Interceptor.java
src/main/java/com/github/wovnio/wovnjava/LanguageAliases.java
src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
src/main/java/com/github/wovnio/wovnjava/ResponseHeaders.java
src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandlerFactory.java
src/test/java/com/github/wovnio/wovnjava/ApiTest.java
src/test/java/com/github/wovnio/wovnjava/CustomDomainLanguageSerializerTest.java
src/test/java/com/github/wovnio/wovnjava/CustomDomainLanguageTest.java
src/test/java/com/github/wovnio/wovnjava/CustomDomainLanguageValidatorTest.java
src/test/java/com/github/wovnio/wovnjava/CustomDomainLanguagesTest.java
src/test/java/com/github/wovnio/wovnjava/CustomDomainUrlLanguagePatternHandlerTest.java
src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
src/test/java/com/github/wovnio/wovnjava/LangTest.java
src/test/java/com/github/wovnio/wovnjava/LanguageAliasSerializerTest.java
src/test/java/com/github/wovnio/wovnjava/LanguageAliasesTest.java
src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
src/test/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandlerTest.java
src/test/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandlerTest.java
src/test/java/com/github/wovnio/wovnjava/TestUtil.java
src/test/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandlerFactoryTest.java
src/test/java/com/github/wovnio/wovnjava/UrlPathTest.java
src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java

Simply removes unused imports.

[refactor] Removed unused imports.

---

pom.xml

Just bumping minor version for re release.

---

pom.xml

Bumped version to 1.9.0 after quality of life improvements. For new release.

Bumped minor version to 1.9.0

---

Makefile
docker/java8/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/WovnHttpServletResponse.java
src/test/java/com/github/wovnio/wovnjava/WovnHttpServletResponseTest.java

https://wovnio.atlassian.net/browse/ST-940
Turns out it's just a terrible string equality check error. The setHeader method don't see any matching header, and therefore is not translating anything.
Included is also a minor change in the makefile. Added a new constant that represents wovnjava's version.

Fixed incorrect string quality check

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/FileExtensionMatcher.java
src/main/java/com/github/wovnio/wovnjava/HtmlChecker.java
src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
src/test/java/com/github/wovnio/wovnjava/FileExtensionMatcherTest.java
src/test/java/com/github/wovnio/wovnjava/HtmlCheckerTest.java

This is identical to https://github.com/WOVNio/wovnjava/pull/183
JDK7 specific change.

Update ignore file extension jdk7

---

Makefile
docker/java8/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlChecker.java
src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
src/test/java/com/github/wovnio/wovnjava/HtmlCheckerTest.java
src/test/java/com/github/wovnio/wovnjava/TestUtil.java
src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java

https://wovnio.atlassian.net/browse/ST-1150
Added checks on the response status code to determine if a response should be translated or not.
status code < 200: not translated
300 <= status code < 400: not translated

Do not send certain requests to html-swapper

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java

java7 version of https://github.com/WOVNio/wovnjava/pull/190

fix: rename ref="alternate" -> rel="alternate" (1.3.1-java7)

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java

I'll cherry-pick from java7 fix.

fix: rename ref="alternate" -> rel="alternate" for java6

---

Makefile
README.en.md
docker/java8/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/main/java/com/github/wovnio/wovnjava/UrlResolver.java
src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
src/test/java/com/github/wovnio/wovnjava/UrlResolverTest.java

https://wovnio.atlassian.net/browse/ST-1251
- added support for fixedScheme, fixedPort and fixedHost options.
Hold until https://github.com/WOVNio/html-swapper/pull/697 is deployed.

[ST-1251] Provide a port and host override for WOVN.java

---

README.md
pom.xml
src/main/java/com/github/wovnio/wovnjava/Settings.java
src/main/java/com/github/wovnio/wovnjava/UrlResolver.java
src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
src/test/java/com/github/wovnio/wovnjava/UrlResolverTest.java

https://wovnio.atlassian.net/browse/SUP-1226

Cherry-pick fixedScheme/Port/Host support to java7

---

Makefile
docker/java8/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/Api.java

https://wovnio.atlassian.net/browse/SUP-1257
If Proxy.NO_PROXY is set it will override any existing global proxy settings.

Fix global proxy support java8

---

.circleci/config.yml
docker/java6/Makefile
docker/java6/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/Api.java
src/main/java/com/github/wovnio/wovnjava/tls/TLSAuthentication.java
src/main/java/com/github/wovnio/wovnjava/tls/TLSClient.java
src/main/java/com/github/wovnio/wovnjava/tls/TLSSession.java
src/main/java/com/github/wovnio/wovnjava/tls/TLSSocket.java
src/main/java/com/github/wovnio/wovnjava/tls/TLSSocketFactory.java
src/test/java/com/github/wovnio/wovnjava/ApiTest.java

Taken from https://github.com/a--i--r/TLSSocketFactory
I confirmed that when testing against https://tls-v1-2.badssl.com:1012/ , without these changes you would get a handshake error. Afterwards, it can send a request succcessfully.

TLS 1.2 implementation

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

Resolves an XSS vulnerability for the Java 7 build.
https://wovnio.slack.com/archives/C01ALMH3BBL/p1661844565924119
https://wovnio.atlassian.net/browse/SUP-1666

[SUP-1666] [java7] add jsoup.clean to removeForm() htmlreplacemarker function

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

fixes content being removed during sanitization

[java7] replace jsoup.clean with .replaceall for quotes

---

Makefile
docker/java8/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

fixes content being removed during sanitization

 [master] replace jsoup.clean with .replaceall for quotes

---

Makefile
docker/java6/Makefile
docker/java6/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

also adds more testcases
fixes content being removed during sanitization

[java6] replace jsoup.clean with .replaceall for quotes

---

Makefile
docker/java6/Makefile
docker/java6/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

This PR will make `removeForm()` also convert `&` into `&amp;` when sanitizing forms.
Java6 version of https://github.com/WOVNio/wovnjava/pull/221

[Java 6] Convert ampersands to &amp; when sanitizing forms

---

Makefile
README.en.md
README.ja.md
docker/java8/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/Lang.java

This replaces es-RA with es-AR.

fix: replace es-RA with es-AR

---

Makefile
docker/java6/Makefile
docker/java6/hello/pom.xml
pom.xml
src/main/java/com/github/wovnio/wovnjava/HtmlReplceMarker.java
src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java

fix(java6): [SUP-2251] `wovn-marker` doesn't restore text properly

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/Lang.java

https://github.com/WOVNio/wovn-lang/pull/34

add mn, uz lang codes

---

pom.xml
src/main/java/com/github/wovnio/wovnjava/Api.java
src/main/java/com/github/wovnio/wovnjava/ResponseHeaders.java
src/test/java/com/github/wovnio/wovnjava/ApiTest.java
src/test/java/com/github/wovnio/wovnjava/TestUtil.java

https://wovnio.atlassian.net/browse/ST-3320
https://github.com/WOVNio/html-swapper/pull/1044

feature: [ST-3320] send response status code to html swapper
