WOVNio/wovnjava

- .idea/libraries/Maven__xerces_xercesImpl_2_11_0.xml
- .idea/libraries/Maven__xml_apis_xml_apis_1_4_01.xml
- pom.xml
- wovn-servlet-filter.iml
htmlparser does not work with old xercesImpl. It is not written in its pom.xml. So I wrote the dependency to wovnjava's pom.xml.
> Add xercesImpl 2.11.0 to dependencies.

- licenses/LICENSE-commons-logging.txt
- licenses/LICENSE-htmlparser.txt
- licenses/LICENSE-jsonic.txt
- licenses/LICENSE-xercesImpl.txt
- licenses/LICENSE-xml-apis.txt
- licenses/NOTICE-commons-logging.txt
- licenses/NOTICE-xercesImpl.txt
- licenses/README.txt
- pom.xml
If we distribute wovnjava-?.?.?-jar-with-dependencies.jar from GitHub, we need to enclose license files of dependencies.
> Add license files of dependencies.

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
There is some case that Apache HTTP Server with mod_rewrite is running in front of Java application. If wovnjava cannot get original URL, wovnjava cannot get translation data from API server. For resolving this problem, I have added "originalUrlHeader" and "originalQueryStringHeader" settings.
You use "REDIRECT_URL" and "REDIRECT_QUERY_STRING" headers or original headers you configured in Apache setting. I will write documentation with some examples.
> Support rewriting URL case.

- Vagrantfile
An error occurs in environment without vagrant plugin.
> Comment out some settings in Vagrantfile.

- README.md
- README_ja.md
- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
from documentation.
> (This is an experimental setting. So it is possible to remove this setting in the future.)
> 
> wovnjava with default settings translates only HTML requests and wovnjava determines data type of response body by only Content-Type. When you set true to srictHtmlCheck setting, wovnjava determines data type of response body not only by Content-Type but also by the content of response body. This setting is used when you want to eliminate HTML responses that has wrong Content-Type.
> Implment strictHtmlCheck setting.

- README.md
- README_ja.md
query documentation was incorrect.
> Fix documentation

- README.md
- README_ja.md
- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/Store.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
For clarity in the communication with user, we need to use the name project token everywhere instead of user token
Related to: https://github.com/WOVNio/equalizer/issues/4057
> replacing user_token with project_token

- .travis.yml
- src/main/java/com/github/wovnio/wovnjava/Doctype.java
- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
Relate: https://github.com/WOVNio/equalizer/issues/6792
Keep doctype when translate html.
Because `HtmlDocumentBuilder` that library remove doctype when create DOM tree.
Update JDK version in .travis.yml
- Add Open JDK 8  
Because Oracle JDK 8 is supported.
- Remove Oracle JDK 7  
Because [that version of the JDK is no longer current ](http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html)
- Remove Open JDK 6  
Because [Sun/Oracle JDK 6 is not provided because it reached End of Life in fall 2012.](https://docs.travis-ci.com/user/reference/precise/)
I confirmed jeff about remove JDK6.
> Keep doctype when translate html

- src/main/java/com/github/wovnio/wovnjava/FixHtml.java
- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/FixHtmlTest.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/TranslateTest.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
I found problem that appear extra invalid closing tag if to use [saxon](http://saxon.sourceforge.net/).
For example.
```
<!doctype html><html lang="ja">
<head>
<title>Link changing test</title>
<meta content="test" name="author">
</head>
 
<body>
hello
<br>
</body>
</html>
```
```
<!doctype html><html lang="ja">
<head>
<title>Link changing test</title>
<meta content="test" name="author"></meta>
</head>
 
<body>
hello
<br></br>
</body>
</html>
```
I guess it is take times to investigate, so I added `deleteInvalidClosingTag` option for temporary solution.
> Implement deleteInvalidClosingTag option

- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
If the browser access with language code by query, wovnjava do internal redirect to other path but it's illegal.
So I fixed it.
This issue reported by our user.
> Only internal redirect when urlPattern is path

- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
The testing code has a `TestUtil.java` file but it was not being used much. This change will take advantage of TestUtil to centralize configuration initializations in all the tests, and it cleans up some related redundant code.
This will make it easier to manage the test when the code changes.
> Centralize testing initialization for FilterConfig mock class.

- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
Fix for https://github.com/WOVNio/equalizer/issues/11688
This is the change to set target lang to target lang instead of default lang after ApiException happened.
Because currentLang make widgets swap even if  ApiException happened,
> Fix current lang to use target lang on handling timeout error

- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
> [prime]kanematsu: search text show wrong encoding
[issue/12121](https://github.com/WOVNio/equalizer/issues/12121)
We made a form and tried it, but we could not reproduce the same problem.
However, since unnecessary redirection has occurred, changed the redirect condition slightly.
This change may solve the problem, so need to have the customer test it.
> remove unnecessary redirect.

- README.md
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/WovnHttpServletResponse.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
If `flushBuffer()` gets called on the ServletResponse, it commits changes to the response such that we can no longer change headers. However, wovnjava relies on changing `content-length` because we alter the size of the response.
Here is from [Oracle docs](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletResponse.html#flushBuffer--):
```
void flushBuffer()
throws IOException
Forces any content in the buffer to be written to the client. A call to this method
automatically commits the response, meaning the status code and headers will be written.
```
Using the library with a servlet deployed on WebLogic, the response was flushed before reaching our filter, which made us unable to change `content-length` to a bigger value. Therefore, the last part of the document was lost.
Request …
> Disable super.flushBuffer on response wrapper

- README.md
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
sitePrefixPath lets the customer set a prefix path to use as an anchor for which WOVN will translate pages. With this setting, WOVN will only translate pages that match the prefix path, and the path language code will be added after the prefix path.
With this setting the following behaviors are affected
* Only process requests that match prefix path
* Detect language code in request path after matching prefix path
* Insert hreflangs with language code after matching prefix path
* Send sitePrefixPath setting in snippet settings (if the setting is used)
* Send sitePrefixPath setting in request to translation API (always)
> Create feature sitePrefixPath

- README.md
- src/main/java/com/github/wovnio/wovnjava/Settings.java
`supportedLangs` is an important setting, and this adds instructions for it to the README.
In order to help configure it, we also include a list of languages that WOVN can support.
Also, `"en"` is no longer included in `supportedLangs` by default.
This setting should probably be a required setting. For now, we don't change configuration requirements.
> Document supportedLangs setting

- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
When translating by API, we set a meta tag to declare content-type UTF-8.
With this change, we insert this meta tag also when processing the request without using the API for translation. Any existing content-type declaration will be replaced.
> Set content-type to UTF-8 also for fallback method

- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/ApiException.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/main/java/com/github/wovnio/wovnjava/ResponseHeaders.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
- src/test/java/com/github/wovnio/wovnjava/ResponseHeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
Improve debugging by including information about the request handling in HTTP header fields.
* Include Fastly HTTP headers from the API response
- `X-Wovn-Cache`
- `X-Wovn-Cache-Hits`
- `X-Wovn-Surrogate-Key`
* Set HTTP headers for the status of API request
- `X-Wovn-Api`
- `X-Wovn-Api-Status`
* Whenever wovnjava touches the request, declare itself in HTTP header
- `X-Wovn-Handler`
* Adjusted ApiException management to make it simpler to declare such errors in `X-Wovn-Api` header field
* Remove dynamic setting of `data-wovnio-type` snippet attribute
- The value is now always set to `fallback` for when wovnjava processes the HTML response
- Once the widget has been updated, this attribute will declare wovnjava version
* In the cache key for translation API request, wovnjava will now …
> HTTP header debugging fields

- README.md
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/RequestOptions.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
- src/test/java/com/github/wovnio/wovnjava/RequestOptionsTest.java
* Add server-side debugMode setting
* Query parameters to change the behavior of wovnjava
- `wovnDisable`
- always available
- wovnajva does nothing
- `wovnCacheDisable`
- only available if debugMode is activated server-side
- bypass translation API cache
- `wovnDebugMode`
- only available if debugMode is activated server-side
- bypass translation API cache
- send `debug_mode=true` to translation API
- opportunity to embed debugging information in the response HTML
* Always send product and version information to translation API
* Bump version to 0.5.0
> Add support for debugging query parameters

- src/main/java/com/github/wovnio/wovnjava/HtmlChecker.java
- src/test/java/com/github/wovnio/wovnjava/HtmlCheckerTest.java
Files like ZIP, TAR, RAR and gziped should not be intercepted.
> Stop Intercepting archive files

- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
Update site prefix path snippet setting to use camel case.
The corresponding widget change will go out next release.
> Use camelCase for snippet settings

- .circleci/config.yml
- .travis.yml
travisci depreated oraclejdk8 environment.
need to create oraclejdk ci environment.
This PR create orackejdk8 env into circleci, and remove travisci env.
> Migrate travisci to circleci

- .circleci/config.yml
- .travis.yml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
Site prefix path has two settings variables.
* `sitePrefixPathWithoutSlash` is the common format
* `sitePrefixPathWithSlash` is only being used one place
With these changes,
1. remove `sitePrefixPathWithSlash` and always access the common format
2. rename `sitePrefixPathWithoutSlash` to just `sitePrefixPath`
> Simplify sitePrefixPath settings

- .circleci/config.yml
This PR change image for oraclejdk to another circleci image.
The name of image for `oraclejdk` env was `circleci/openjdk:8-jdk` .
It can lead to mis-understanding.
Additionally, update cache key for use cache.
> [MISC] Update circleci env

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandler.java
- src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandlerTest.java
Move `removeLang` logic from Headers into the respective PatternHandlers.
Logic remains unchanged.
> [Refactor] Move removeLang into PatternHandlers

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
* Rename `pathLang` to `requestLang`.
* Calculate `requestLang` only once, when Headers is instantiated. Change the getter to simply return the value.
Logic for calculating the value remains unchanged.
> [Refactor] Calculate requestLang at Headers initialization

- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/main/java/com/github/wovnio/wovnjava/Lang.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandler.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/LangTest.java
- src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/RequestOptionsTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
Change to allow Lang lookup only by language code. This fixes some incorrect behaviors in URL handling. `Lang.java` is greatly simplified in the process.
Note that in the Lang initialization, information for the names of languages is kept in the file, but it is no longer being used by the library.
* Lang object lookup only uses language code now
- This affects URL matches and settings configuration
* Raise ConfigurationError if the setting for defaultLang or supportedLangs is invalid
- This is added now because a configuration like `defaultLang=English` becomes invalid
* Access ISO639-1 language code for hreflang using a Lang field instead of conversion function
* (Whitespace changes) retab test files for UrlLanguagePatternHandlers
> Allow Lang lookup only by language code

- src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
- src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandlerTest.java
Fix bugs with `removeLang` for when `urlPattern=path`, and improve test cases for all removeLang variations.
* Fix PathUrlLanguagePatternHandler to only match path lang code at the beginning of the path
* Add test cases for when the input URL includes schema (this was also broken for urlPattern path)
- now we should be able to pass a URL of any form into `removeLang` and see expected behavior
> Fix and improve tests for removeLang

- src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandler.java
- src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandlerTest.java
We want `getLang(url)` to find the language code of URLs of any form.
Specifically, these changes make sure that URLs with schema, of the form `http://site.com/path?query`, are matched correctly by all UrlLanguagePatternHandlers. Test cases are added to that effect.
Lastly, the regexes supporting getLang are all given comments explaining what they do.
> Fix and improve tests for getLang

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/UrlResolver.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/UrlResolverTest.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
Create static class UrlResolver for correctly computing client request URL. The priority for URL fields to use for this purpose is
1. HTTP headers
2. Internal servlet container request forwarding attributes
3. Current request values
Using values from HTTP headers is dependent on user configuration (such as `useProxy` setting). If configuration is set to use HTTP headers but the relevant HTTP headers are not set, UrlResolver will resolve the URL normally.
Current requestLang is determined based on the client request URL.
> Compute client request URL

- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
HTTP Header `Location` is currently not used, but it is being mocked and "tested"
> [Misc] Remove references to HTTP header "Location"

- src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
- src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
For path patterns, `removeLang` has incorrect interaction with query parameters in URL when path is empty (example: `site.com?query`). These changes apply a fix for it and expands test cases.
Also, the changes include a fix to trailing slash after removing language code. If the path ends like `/path/ja`, the resulting path without language code should not have trailing slash, like `/path`. If the original path ends with slash like `/path/ja/`, the resulting path should be `/path/`.
> [Fix] Path pattern removeLang

- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
WovnServletFilter may intercept a single request multiple times if the request is forwarded internally within the servlet container. For instance, this forwarding happens when WovnServletFilter forwards a request with language code to the same request without language code.
WovnServletFilter will always set HTTP header `X-Wovn-Handler` when intercepting a request. Therefore, with these changes we will check if that header is set on the response object before processing the request. If the header is set, we will ignore it and pass it through untouched.
This change is more important now than before because we now calculate the request language etc based on the client requested URL, not the current servlet URL.
> Process each request only once

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/Lang.java
- src/test/java/com/github/wovnio/wovnjava/LangTest.java
This change is a small adjustment to the naming for our language codes use in hreflangs.
> [Misc] Adjust naming for language codes used in hreflangs

- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/UrlPath.java
- src/test/java/com/github/wovnio/wovnjava/UrlPathTest.java
Update translation API request to use the computed client request URL to identify which page is being translated.
The API request puts this information in two places. It sends the full URL in the API body, and it sends just the path in the cache key. We therefore have to extract the path part, and a new helper function is added for this purpose.
We use quite a bit of regex manipulation for URLs at this point. A lot of it is unavoidable, of course, and I'm trying to think about how to keep it to a minimum. That said, as long as any regex manipulation is tested in isolation, it feels manageable.
> [Fix] Send correct client request URL in translation API request

- README.md
- README_ja.md
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
The `secretKey` setting has never been used and is not needed, so we remove it.
Existing configuration files do not need to be changed.
> Remove secretKey setting

- README.md
- README_ja.md
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
The purpose of the `query` setting is to identify unique pages when the specified query parameters are different. This is a setting that the customer configures for their Wovn project.
The standard behavior for our products is to include all query parameters in the request for page data, and the server will identify the page correctly. Therefore, wovnjava does not need to concern itself with the details of query parameter filtering, and we can remove the setting.
Existing configuration files do not need to be changed.
**Old behavior:** Send only the query parameters required to identify the page
**New behavior:** Send all query parameters always, and let the server pick query parameters for page identification
> Remove query setting

- src/main/java/com/github/wovnio/wovnjava/FileExtensionMatcher.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/HtmlChecker.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/FileExtensionMatcherTest.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/HtmlCheckerTest.java
This PR makes two structural changes. The primary purpose is to clean `Headers.java` of legacy URL parsing code.
The Headers class has several fields and a lot of code related to request URL that we are removing.
```java
String host;
String pathName;
String pathNameKeepTrailingSlash;
String protocol;
String pageUrl;
String query;
String url;
```
Only two of these fields are still in use outside of Headers, `pathName` and `pathNameKeepTrailingSlash`. They are used for purposes that need the _location of the current servlet context_.
For all other request URL handling, we need the _location originally requested by the client_. This URL handling is already moved to `UrlResolver.java` (and is now stored in Headers as `clientRequestUrlWithoutLangCode`).
Instead of the old `pathName` and …
> Create FileExtensionMatcher and clean up Headers

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
For some received requests, the filter needs to do nothing.
If the request has already been processed by wovnjava (and redirected, such that we receive it a second time), we should do nothing. We can assume that all necessary URL manipulation etc is already taken care of.
Also, if the request URL does not match the set of URLs that wovnjava is configured to process, we should not attempt to manipulate the URL by removing language code. We should instead do nothing. Such requests may happen if `sitePrefixPath` is set, and it will be relevant for Custom Domain.
This PR also changes a couple of names to be more general, so that we can more easily apply them to Custom Domain.
> Do nothing for invalid or previously processed requests

- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
- src/test/java/com/github/wovnio/wovnjava/MockHttpServletRequest.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
* Create a class for mocking HttpServletRequest objects in our tests. Remove the other `mockRequestPath` methods spread across our tests.
* Reduce implied defaults by making tests declare the full URL of the mocked request.
> Centralize mock for HttpServletRequest

- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/UrlContext.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
With Custom Domain, URLs in default language may include language code. This PR simply renames some variables to suit the new assumptions about the nature of our URLs.
> Rename URL variables to be generic

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/UrlContext.java
UrlContext is used as base URL for forwarding relative URLs internally.
We intercept the forwarding call because we want to make sure to strip Wovn language code from the current URL context, such that it is as transparent as possible to introduce wovnjava to an existing server.
Currently, UrlContext is based on the client request URL. However, if the request has been altered by a reverse proxy, the current URL context may be different from the original request, and our "base URL" may be incorrect at the point where the internal forwarding happens.
I want to change the UrlContext object to be based on the location of the current internal context.
In summary, when manipulating a request URL that may have changed, I think we should
1) Determine the language of the request from the original …
> Base UrlContext on the current servlet context URL

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/WovnHttpServletRequest.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
Currently when we intercept a request, we sometimes forward it with a different path (internally in the servlet container). This happens when the request path is different from the path in default language, such as when receiving `site.com/en/page.html` and `urlPattern = path`. We will forward that request to `site.com/page.html`.
However when we _don't_ need to translate the incoming request, such as for an image resource, we currently never forward it. Instead, the wrapper for the request object will try to hide language codes when accessing information about the path.
Hiding language codes from the getters on the request object is difficult because of how the servlet context influences the correct response, particularly for getters on the URL path. This stackoverflow post illustrates …
> Always forward to path in default language

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandlerFactory.java
- src/main/java/com/github/wovnio/wovnjava/WovnHttpServletRequest.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/LangTest.java
- src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandlerTest.java
When checking language code of a URL, ignore any language code that is not declared by the user in `supportedLangs` setting.
For example, if supported languages include only English and Japanese, do not consider the `/th/` in `http://site.com/th/page` as a Thai language code.
Also, refactor `getLang` to return Lang object instead of String, or null if no language code is found.
> Ignore URL language codes that are not declared in supportedLangs

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/WovnHttpServletRequest.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/MockHttpServletRequest.java
- src/test/java/com/github/wovnio/wovnjava/WovnHttpServletRequestTest.java
We want to better control what our URL manipulation inputs and outputs are, so guarantee that our inputs are full URLs.
The only remaining incomplete URL sent as input to UrlLanguagePatternHandler originates from `WovnHttpServletRequest.getRemoteHost()`. This PR changes the way we ask to remove language from `request.getRemoteHost()`, such that the language handlers always receive full URLs.
> Always send complete URLs to UrlLanguagePatternHandlers

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandler.java
- src/test/java/com/github/wovnio/wovnjava/PathUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/QueryUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/SubdomainUrlLanguagePatternHandlerTest.java
Adjust interface to `insertLang` method
* Rename to `convertToTargetLanguage`
* Pass in a Lang object instead of language code string
* In existing pattern handlers, remove language code from input URL before inserting new language
> Change insertLang to convertToTargetLanguage

- README.md
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/CustomDomainLanguage.java
- src/main/java/com/github/wovnio/wovnjava/CustomDomainLanguageSerializer.java
- src/main/java/com/github/wovnio/wovnjava/CustomDomainLanguageValidator.java
- src/main/java/com/github/wovnio/wovnjava/CustomDomainLanguages.java
- src/main/java/com/github/wovnio/wovnjava/CustomDomainUrlLanguagePatternHandler.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandlerFactory.java
- src/main/java/com/github/wovnio/wovnjava/ValidationResult.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
- src/test/java/com/github/wovnio/wovnjava/CustomDomainLanguageSerializerTest.java
- src/test/java/com/github/wovnio/wovnjava/CustomDomainLanguageTest.java
- src/test/java/com/github/wovnio/wovnjava/CustomDomainLanguageValidatorTest.java
- src/test/java/com/github/wovnio/wovnjava/CustomDomainLanguagesTest.java
- src/test/java/com/github/wovnio/wovnjava/CustomDomainUrlLanguagePatternHandlerTest.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/UrlLanguagePatternHandlerFactoryTest.java
Custom Domain is a URL pattern configuration alternative to path, query, and subdomain. It can specify the domain and path corresponding to each language independently.
Example domain and path mapping to original language Japanese plus two target languages:
```
"www.site.co.jp"       -> Japanese
"www.site.com/english" -> English
"spain.site.com"       -> Spanish
```
For this example mapping, the URL `http://www.site.co.jp/about.html` will map to the three languages as follows
```
Japanese  -> "http://www.site.co.jp/about.html"
English   -> "http://www.site.com/english/about.html"
Spanish   -> "http://spain.site.com/about.html"
```
The corresponding `web.xml` configuration looks as follows
```xml
<filter>
...
<init-param>
<param-name>defaultLang</param-name>
<param-value>ja</param-value> …
```
> Support Custom Domain configuration

- README.md
README description for parameters needs an update. Settings are revamped, and much of the current information is outdated.
I changed the order in which parameters are listed in order to describe required parameters first, and to couple related paramters.
> Update parameter descriptions in README

- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
Hreflang elements are currently selected by iterating over a HashMap, which has undefined order.
Change implementation to use LinkedHashMap instead which iterates over elements in inserted order, such that tests do not change needlessly when compiling the library with various JDKs etc.
As a result, hreflang elements will now be inserted in the same order as specified in the `supportedLangs` setting.
> Use LinkedHashMap for deterministic hreflang ordering

- README.md
- README_ja.md
- src/main/java/com/github/wovnio/wovnjava/FilterConfigReader.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/FilterConfigReaderTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
- Added a new `showVersion` setting.
Set showVersion to false, you can hide the version number of the X-Wovn-Handler header.
Note: Since there was a request for java7_support, java7_support will be merged with master and java6_support in the same way.
> Hide version number option

- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
Don't need to set the character code the content-type is not HTML.
Fixed a bug that it is converted to image/png;charset=utf-8 when content-type is image/png.
> [Fix] Changed character encoding only when converting HTML

- pom.xml
- src/main/java/com/github/wovnio/wovnjava/HtmlChecker.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/HtmlCheckerTest.java
If it is possible to convert to utf-8, all things such as images will be converted to utf-8, so confirm the Content-Type to convert only text or json.
Note: In the future, may need the option to exclude some URLs or Content-Types.
The test implementation to verify the HTTP header has not yet been implemented, so I will attach the local verification results for the time being.
It is noteworthy that no unnecessary character codes have been added to the Content-Type.
BEFORE: 
AFTER:
> Fixed the problem of converting everything to UTF-8

- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
Revert https://github.com/WOVNio/wovnjava/pull/159
The code is basically correct in how we are installing BouncyCastle, but there are several environment problems we weren't aware of.
```
Caused by: java.security.NoSuchAlgorithmException: Algorithm ECDH not available
at javax.crypto.KeyAgreement.getInstance(DashoA13*..)
```
```
com.github.wovnio.wovnjava.ApiException: Exception : unable to create JcaTlsCrypto: SecureRandom DEFAULT implementation not found: java.lang.ClassNotFoundException: org.bouncycastle.jcajce.provider.drbg.DRBG$Default
at com.github.wovnio.wovnjava.Api.translate(Api.java:69)
```
For now I am reverting this change until we understand these issues more. I suspect there is a problem with the fat jar packaging we are doing. …
> Revert: Add TLS 1.2 support for java 6

- pom.xml
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
https://wovnio.atlassian.net/browse/ST-599
When an HTML is converted, if the `<html>` tag doesn't have a `lang` attribute, the default language will be added.
Before: `<html><head>...`
After: `<html lang="en"><head>...`
> [Feature] Add insert doc lang feature.

- .circleci/config.yml
- .gitignore
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
https://wovnio.atlassian.net/browse/ST-826
Snippets like `<script src="https://wovn.global.ssl.fastly.net/widget/abcdef">` should also be considered a widget snippet and removed.
> Check for widget versioning snippets

- CONTRIBUTE.md
- README.en.md
- docker/README.md
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/Utf8.java
- src/main/java/com/github/wovnio/wovnjava/WovnHttpServletResponse.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/Utf8Test.java
https://wovnio.atlassian.net/browse/ST-983
Added a new setting item called `encoding`, when set, wovnjava will use that encoding to handle all strings. If not set, wovnjava will attempt to determine the encoding from a predetermined list of encodings.
> [ST-983] Allow explicit encoding setting

- Makefile
- docker/java8/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/FileExtensionMatcher.java
- src/main/java/com/github/wovnio/wovnjava/HtmlChecker.java
- src/main/java/com/github/wovnio/wovnjava/WovnHttpServletResponse.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/FileExtensionMatcherTest.java
- src/test/java/com/github/wovnio/wovnjava/HtmlCheckerTest.java
Changes:
- added two new file extensions into the list of "should not translate"
- changed how we detect if a file is binary/needs UTF-8 conversion treatment
- before: we load the entire file and see if we can convert it to a string (this doesn't work, as you always get _some_ string back)
- after: we look at the content-type, only those that have `text/` in them are not binary + needs UTF-8 conversion.
Other changes:
- updated make file to make stale build artifacts less likely to exist
> Update ignore file extension

- Makefile
- docker/java8/hello/pom.xml
- docker/java8/hello/src/main/java/com/example/wovnjava/hello/UniversalFilter.java
- docker/java8/hello/src/main/webapp/WEB-INF/web.xml
- pom.xml
This PR is a quality of life PR that improves debugging using the docker environment. A new filter is provided in the java8 docker example website.
Most notably, this PR adds the ability to send a request to any route prefixed by `/custom_response`, and dictate what the response should be.
You can decide:
- Response headers
- Response HTTP status code
- Response body
- You need to include a JSON body with such requests:
```
{
"response": {
"body": "foo2",
"content-type": "text/html",
"status": 200,
"headers": { "X-WovnTest": "Foo" }
}
}
```
Theoretically speaking, content-type is also a header, but it is included in its separate field.
> Added Support for Universal Routes in Docker Env

- Makefile
- docker/java8/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/ApiNoPageDataException.java
- src/main/java/com/github/wovnio/wovnjava/Interceptor.java
- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/InterceptorTest.java
- src/test/java/com/github/wovnio/wovnjava/MockHttpServletRequest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
https://wovnio.atlassian.net/browse/SUP-969
With this PR, an HTTP 422 status code returned from html-swapper no longer results in an unhandled exception being thrown.
- Added new exception `ApiNoPageDataException`, thrown when the html-swapper response code is 422
- The `ApiNoPageDataException` is caught and the request is processed the same way as other failed swaps
- `X-Wovn-Api-Status: ApiDataNotAvailable` header is added to all responses where `ApiNoPageDataException` is caught
- Fixed misc. code warnings (unused variables etc)
> [SUP-969] Add Handling of 422 API Error

- Makefile
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/SettingsTest.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
Added support for widget versioning.
- added a required option `snippetUrl` that should be set to the URL of the snippet.
-  if not set, `https://j.wovn.io/1` will be used
> [ST-1104] Added support for widget versioning url.

- Makefile
- README.en.md
- docker/java8/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/FilterConfigReader.java
- src/main/java/com/github/wovnio/wovnjava/FormUrlEncoding.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/FilterConfigReaderTest.java
- src/test/java/com/github/wovnio/wovnjava/FormUrlEncodingTest.java
wovnio.atlassian.net/browse/ST-1100
We currently gzip the request to html swapper. There is now a compress_api_request setting that can be set to false to disable this.
This is only to make it easier to use MockServer to assert the incoming request as JSON in integration tests.
Small refactor to stop constructing a url encoded string manually and generate it from a Map instead.
> feature: [ST-1100] Add compressApiRequests setting, defaulted to true.

- docker/java7/hello/src/main/webapp/WEB-INF/web.xml
- docker/java8/hello/src/main/webapp/WEB-INF/web.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
- remove comments from web.xml (easier for integration tests to replace these variables)
- send lang_param_name setting to html swapper (not implemented via settings yet)
> refactor: integration test fixes

- Makefile
- docker/java8/hello/pom.xml
- pom.xml
No actual code changes. Some build artifacts on 1.11.0 have been lost somehow like https://jitpack.io/com/github/wovnio/wovnjava/1.11.0/wovnjava-1.11.0.pom
> bump to 1.11.1 to refresh jitpack

- Makefile
- docker/java8/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
https://wovnio.atlassian.net/browse/ST-1216
`simple_json` was used to serialize the request body because it produces a more "sane" serialized string. (Only down side is that it also escapes `/` as `\/`)
When serializing with `jsonic` too many characters get unicode escaped and it's very unreadable.
> Add JSON support

- docker/java8/hello/src/main/webapp/WEB-INF/web.xml
By default, filters are only executed for browser requests. When browsing to `/ja/custom_response`, the wovn filter will execute first, remove `/ja/` and call `requestDispatcher.forward()` which starts a separate request pipeline. UniversalFilter won't be executed in this pipeline unless given `FORWARD` permission in the filter list.
Note that this UniversalFilter is only part of the test docker website so we can craft any kind of origin request for testing purposes.
> tests: Enable forwarding for UniversalFilter, so it can be forwarded from the wovn filter

- Makefile
- README.en.md
- docker/java8/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/Headers.java
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/test/java/com/github/wovnio/wovnjava/ApiTest.java
- src/test/java/com/github/wovnio/wovnjava/HeadersTest.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
- src/test/java/com/github/wovnio/wovnjava/MockHttpServletRequest.java
https://wovnio.atlassian.net/browse/ST-1269
1. Add `api_timeout_search_engine_bots` setting. Having a longer timeout for search engines makes it more likely they will receive a translated version of the page.
2. Add `translate_canonical_tag` setting. This setting adds lang codes to `<link rel="canonical" href="">` tags in the fallback snippet HTML. In the event our API request does time out,  it should not negatively impact SEO. This can be set to `false` to disable translating this tag completely (including in html swapper)
> feature: [ST-1269] translate canonical url + search engine api timeout settings

- .circleci/config.yml
- Makefile
- docker/java8/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/Diagnostics.java
- src/main/java/com/github/wovnio/wovnjava/RequestOptions.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/WovnLogger.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
https://wovnio.atlassian.net/browse/SUP-1501?focusedCommentId=49877
Setting Content-Length header isn't mandatory but can lead to truncation if not set correctly.
Also added some convenience debugging utilities while investigating this issue:
- Add `wovnEncodingOverride` debug query parameter to force the response encoding when wovnjava receives the original HTML. Only available in debug mode. There is an `encoding` setting in the wovnjava configuration file, but this allows us to change the encoding for a single request.
- `wovnDebugMode` now shows the request logs as a HTML comment for debugging purposes (when debug mode is enabled in settings)
> fix: [SUP-1501] stop setting content-length explicitly to avoid truncating responses

- Makefile
- docker/java6/Makefile
- docker/java6/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
Resolves an XSS vulnerability for the Java 6 build.
https://wovnio.slack.com/archives/C01ALMH3BBL/p1661844565924119
https://wovnio.atlassian.net/browse/SUP-1666
> [SUP-1666] [java6] add jsoup.clean to removeForm() htmlreplacemarker function

- .circleci/config.yml
Use https://hub.docker.com/r/azul/zulu-openjdk image rather than manually crafting one from ubuntu. Delete oracle jobs because they aren't supported anymore anyway.
> Fix openjdk7 circle CI job

- pom.xml
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
This PR will make `removeForm()` also convert `&` into `&amp;` when sanitizing forms.
Java7 version of https://github.com/WOVNio/wovnjava/pull/221
> [Java 7] Convert ampersands -> &amp; when sanitizing forms

- Makefile
- docker/java8/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/HtmlConverter.java
- src/test/java/com/github/wovnio/wovnjava/HtmlConverterTest.java
This PR will make `removeForm()` also convert `&` into `&amp;` when sanitizing forms.
> Convert & -> &amp; when sanitizing forms

- Makefile
- README.en.md
- docker/java8/hello/pom.xml
- pom.xml
- src/main/java/com/github/wovnio/wovnjava/Api.java
- src/main/java/com/github/wovnio/wovnjava/Settings.java
- src/main/java/com/github/wovnio/wovnjava/WovnServletFilter.java
- src/test/java/com/github/wovnio/wovnjava/FilterChainMock.java
- src/test/java/com/github/wovnio/wovnjava/RequestDispatcherMock.java
- src/test/java/com/github/wovnio/wovnjava/TestUtil.java
- src/test/java/com/github/wovnio/wovnjava/WovnServletFilterTest.java
https://wovnio.atlassian.net/browse/ST-2002
https://wovnio.atlassian.net/browse/SUP-2099
New setting: `overrideContentLength`. Default false. When true, we will set/replace Content-Length header based on the size of the translated response.
```
<init-param>
<param-name>overrideContentLength</param-name>
<param-value>true/false</param-value>
</init-param>
```
This code was previously removed in https://github.com/WOVNio/wovnjava/pull/209. In some environments, setting Content-Length causes issues so it is now an optional setting.
Improved `WovnServletFilterTest`. For the first time, we can now assert on the response body.
> feature: [ST-2002] Add overrideContentLength setting to enable setting "Content-Length" header.

- pom.xml
- src/main/java/com/github/wovnio/wovnjava/FileExtensionMatcher.java
- src/test/java/com/github/wovnio/wovnjava/FileExtensionMatcherTest.java
Not being detected as a file means it get encoded incorrectly
> fix: detect CSV as a file
